services:
  app_api:
    container_name: app_api
    image: app_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8080"
    mem_limit: 1g
    cpus: "2.0"
